server:
  port: 9000
spring:
  profiles:
    active: dev, base-addi
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: c##woo
    password: woo
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create